id: 02_gc_flow_scheduled
namespace: healthcare
description: |
  The CSV Data: https://github.com/Kabalkina/healthcare_project/tree/main/data
  CSV uses `;` as separator.

variables:
  file: "23131-0002_en_{{trigger.date | date('yyyy')}}.csv"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"
  table: "{{kv('GCP_DATASET')}}.healthcare_data_staging_{{trigger.date | date('yyyy')}}"
  data: "{{outputs.extract.outputFiles['healthcare_data_' ~ (trigger.date | date('yyyy')) ~ '.csv']}}"

tasks:

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO "healthcare_data_{{trigger.date | date('yyyy')}}.csv" https://raw.githubusercontent.com/Kabalkina/healthcare_project/main/data/{{render(vars.file)}}

  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{render(vars.data)}}"
    to: "{{render(vars.gcs_file)}}"

  - id: bq_healthcare_data
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE TABLE IF NOT EXISTS `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.healthcare_data`
      (
          unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
          filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),
          statistics_code INTEGER,
          statistics_label STRING,
          time_code STRING,
          time_label STRING,
          time INTEGER,
          one_variable_code STRING,
          one_variable_label STRING,
          one_variable_attribute_code STRING,
          one_variable_attribute_label STRING,
          two_variable_code STRING,
          two_variable_label STRING,
          two_variable_attribute_code STRING,
          two_variable_attribute_label STRING,
          three_variable_code STRING,
          three_variable_label STRING,
          three_variable_attribute_code STRING,
          three_variable_attribute_label STRING,
          four_variable_code STRING,
          four_variable_label STRING,
          four_variable_attribute_code STRING,
          four_variable_attribute_label STRING,
          value INTEGER,
          value_unit STRING,
          value_variable_code STRING,
          value_variable_label STRING
      );

  - id: bq_healthcare_table_ext
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE EXTERNAL TABLE `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}_ext`
      (
          statistics_code INTEGER,
          statistics_label STRING,
          time_code STRING,
          time_label STRING,
          time INTEGER,
          one_variable_code STRING,
          one_variable_label STRING,
          one_variable_attribute_code STRING,
          one_variable_attribute_label STRING,
          two_variable_code STRING,
          two_variable_label STRING,
          two_variable_attribute_code STRING,
          two_variable_attribute_label STRING,
          three_variable_code STRING,
          three_variable_label STRING,
          three_variable_attribute_code STRING,
          three_variable_attribute_label STRING,
          four_variable_code STRING,
          four_variable_label STRING,
          four_variable_attribute_code STRING,
          four_variable_attribute_label STRING,
          value INTEGER,
          value_unit STRING,
          value_variable_code STRING,
          value_variable_label STRING
      )
      OPTIONS (
          format = 'CSV',
          field_delimiter = ';',
          uris = ['{{render(vars.gcs_file)}}'],
          skip_leading_rows = 1,
          ignore_unknown_values = TRUE
      );

  - id: bq_healthcare_table_tmp
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE TABLE `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}`
      AS
      SELECT
        MD5(CONCAT(
          COALESCE(CAST(time AS STRING), ""),
          COALESCE(CAST(one_variable_attribute_label AS STRING), ""),
          COALESCE(CAST(two_variable_attribute_label AS STRING), ""),
          COALESCE(CAST(three_variable_attribute_label AS STRING), ""),
          COALESCE(CAST(four_variable_attribute_label AS STRING), "")
        )) AS unique_row_id,
        "{{render(vars.file)}}" AS filename,
        *
      FROM `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}_ext`;

  - id: bq_merge
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      MERGE INTO `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.healthcare_data` T
      USING `{{kv('GCP_PROJECT_ID')}}.{{render(vars.table)}}` S
      ON T.unique_row_id = S.unique_row_id
      WHEN NOT MATCHED THEN
        INSERT (unique_row_id, filename, statistics_code, statistics_label, time_code, time_label, time,
                one_variable_code, one_variable_label, one_variable_attribute_code, one_variable_attribute_label,
                two_variable_code, two_variable_label, two_variable_attribute_code, two_variable_attribute_label,
                three_variable_code, three_variable_label, three_variable_attribute_code, three_variable_attribute_label,
                four_variable_code, four_variable_label, four_variable_attribute_code, four_variable_attribute_label,
                value, value_unit, value_variable_code, value_variable_label)
        VALUES (S.unique_row_id, S.filename, S.statistics_code, S.statistics_label, S.time_code, S.time_label, S.time,
                S.one_variable_code, S.one_variable_label, S.one_variable_attribute_code, S.one_variable_attribute_label,
                S.two_variable_code, S.two_variable_label, S.two_variable_attribute_code, S.two_variable_attribute_label,
                S.three_variable_code, S.three_variable_label, S.three_variable_attribute_code, S.three_variable_attribute_label,
                S.four_variable_code, S.four_variable_label, S.four_variable_attribute_code, S.four_variable_attribute_label,
                S.value, S.value_unit, S.value_variable_code, S.value_variable_label);

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
